### PR TITLE
Separated cycle track -> Remote cycle track

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
New palette, looking good:

image

**Comment by Robinlovelace** [comment]
Results for London, I plan to tweak this:

image

**Comment by Robinlovelace** [comment]
Live update: vs code colour picker is great!

image

**Comment by Robinlovelace** [comment]
Going with the red, amber, green idea in next commit:

image

**Review by wangzhao0217 — APPROVED** [review]
looks good to me :)

**Review by wangzhao0217 — APPROVED** [review]

**Comment by Robinlovelace** [comment]
After cleaning widths, more of Blackfriars Bridth Road cycleway is 'green'/wide: 

image

**Comment by mvl22** [comment]
The use of this gradation colour scheme from good to bad is good.

There is the usual issue of red/green colour scheme for colour-blindness; I think often red to blue is used.

I think the name 'Remote cycle track' is better than before. Does this pick up links between dense areas? I wonder if that will cause confusion.

**Comment by Robinlovelace** [comment]
Good feedback @mvl22, not sure if it picks up links between Dense areas. More soon!

**Comment by mvl22** [comment]
> After cleaning widths, more of Blackfriars Bridge Road cycleway is 'green'/wide:

All of it should be wide, as indeed should Embankment. It is genuinely Dutch-quality infrastructure.

**Pull request merged**
